root = "."
tmp_dir = "storage/tmp"

[build]
bin = "storage/tmp/app"
cmd = "go build -o storage/tmp/app \
  -ldflags=\"-X 'xi/internal/app/lib/cfg/static.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ )' \
             -X 'xi/internal/app/lib/cfg/static.BuildRevision=$(git rev-parse --short HEAD)' \
             -X 'xi/internal/app/lib/cfg/static.BuildMode=test' \
             -X 'xi/internal/app/lib/cfg/static.BuildVersion=$(git describe --tags --match v*.*.* --abbrev=0 2>/dev/null || echo dev)'\" \
  ./cmd/web"
delay = 1000

[log]
time = true
color = true
prefix = "air:"

[watch]
extensions = ["go", "tpl", "tmpl", "html", "toml", "yaml"]
ignore = ["tmp", "vendor", "node_modules"]

[screen]
clear_on_rebuild = true
